name: Workflow Test

jobs:
  creare-release:
    name: Create Release
    steps:
      - name: Create Test Release
        id: create_test_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Test
          body:
          draft: false
          prelease: true
